"""Report generation module."""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from . import __version__
from .analyze import AnalysisResult
from .validate import ValidationResult


@dataclass
class ModernizationReport:
    filename: str
    target: str | None
    improvement_type: str
    description: str
    risk_level: str
    reasoning: str
    success: bool
    validation: ValidationResult | None
    diff: str | None
    failure_reason: str | None = None
    timestamp: datetime = None

    def __post_init__(self):
        self.timestamp = self.timestamp or datetime.now()

    def to_markdown(self) -> str:
        status = "✅ SUCCESS" if self.success else "❌ FAILED"
        syntax = "✅" if self.validation and self.validation.syntax_valid else "❌"
        tests = "✅" if self.validation and self.validation.tests_passed else ("❌" if self.validation and self.validation.tests_passed is False else "⏭️")

        md = f"""# Modernization Report
- **File**: `{self.filename}`
- **Target**: `{self.target or 'N/A'}`
- **Type**: `{self.improvement_type}`
- **Status**: {status}

## Description
{self.description}

## Validation
- Syntax: {syntax}
- Tests: {tests}
"""
        if not self.success and self.failure_reason:
            md += f"\n## Failure\n{self.failure_reason}\n"
        md += f"\n---\nGenerated by Legacy AI Modernizer v{__version__}"
        return md

    def save(self, output_dir: Path) -> Path:
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"report_{self.timestamp:%Y%m%d_%H%M%S}_{self.filename.replace('.py', '')}.md"
        path = output_dir / filename
        path.write_text(self.to_markdown())
        return path


def create_success_report(filename: str, analysis: AnalysisResult, validation: ValidationResult, diff: str) -> ModernizationReport:
    return ModernizationReport(filename, analysis.target, analysis.improvement_type, analysis.description,
                               analysis.risk_level, analysis.reasoning, True, validation, diff)


def create_failure_report(filename: str, analysis: AnalysisResult, validation: ValidationResult | None, reason: str) -> ModernizationReport:
    return ModernizationReport(filename, analysis.target, analysis.improvement_type, analysis.description,
                               analysis.risk_level, analysis.reasoning, False, validation, None, reason)


def create_no_changes_report(filename: str) -> ModernizationReport:
    return ModernizationReport(filename, None, "none", "No safe improvements identified", "none",
                               "Code is already well-structured", True, None, None)
